feat: stonedb initial support
sqlancer/sqlancer pull request #809
Opened 2023-06-08 14:54 UTC by ZhengLin-Li

2023-06-09 14:38 UTC, bajinsheng requested changes

2023-06-09 14:38 UTC, bajinsheng commented on src/sqlancer/stonedb/StoneDBOptions.java
> +@Parameters(separators = "=", commandDescription = "StoneDB (default host: " + MySQLOptions.DEFAULT_HOST
Here, I think you should create a StoneDBOption, as it defines DBMS-specific parameters.

2023-06-09 14:38 UTC, bajinsheng commented on src/sqlancer/stonedb/StoneDBOptions.java
> +@Parameters(separators = "=", commandDescription = "StoneDB (default host: " + MySQLOptions.DEFAULT_HOST
Oh, I just noticed that you have a StoneDBOption class, but do not import anything from MySQLOption class. Define it in StoneDBOption class.

2023-06-09 14:38 UTC, bajinsheng commented on src/sqlancer/stonedb/StoneDBSchema.java
> +            try (ResultSet rs = s.executeQuery("SELECT * FROM sqlite_master WHERE type='table' or type='view'")) {
Is the SQL corrected? Isn't it `SHOW TABLE`?

2023-06-09 14:38 UTC, bajinsheng commented on src/sqlancer/stonedb/StoneDBSchema.java
> +            case TINYINT:
These data types are implemented differently in MySQL, but seem fine-grained and correct with reference to the doc: https://stonedb.io/docs/SQL-reference/data-types?_highlight=data .

Have you checked with the StoneDB doc? If so, it is good.

2023-06-09 14:38 UTC, bajinsheng commented on src/sqlancer/stonedb/StoneDBSchema.java
> +        TINYINT, SMALLINT, MEDIUMINT, INT, BIGINT, FLOAT, DOUBLE, DECIMAL, YEAR, TIME, DATE, DATETIME, TIMESTAMP, CHAR,
For these errors of undefined enum, I would suggest you can simply add definitions of them in corresponding functions to make the PR self-contained.

2023-06-12 01:29 UTC, bajinsheng approved these changes

2023-06-12 02:04 UTC, mrigger commented
It's strange, it seems they are stuck. Not sure if pushing again might help?

2023-06-12 02:28 UTC, oraluben commented
Looks like a github issue, I think close and open a new PR would work.

2023-06-12 03:55 UTC, ZhengLin-Li commented
will close and reopen

2023-06-12 03:55 UTC, closed without merging